//------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated from a template.
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema; // <-- 1. Bunu mutlaka ekleyin

    public partial class review
    {
        public int Id { get; set; }

        public string Comment { get; set; } // Yorum sütunu (Veritabanında varsa ekleyin)

        public Nullable<int> Rating { get; set; }

        // --- DÜZELTİLEN KISIMLAR ---

        [Column("Product_id")] // Veritabanı adını sabitliyoruz
        public int Product_id { get; set; }

        [Column("User_id")] // Eksik olan User_id'yi ekliyoruz
        public int User_id { get; set; }

        public virtual product product { get; set; }
        public virtual user user { get; set; } // Eksik olan 'user' nesnesini ekliyoruz
    }
}