//------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated from a template.
//
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema; // <-- BU ÇOK ÖNEMLİ, BUNU EKLİYORUZ

    public partial class stock_movement
    {
        public int Id { get; set; }
        public string Movement_type { get; set; }
        public Nullable<System.DateTime> Movement_date { get; set; }
        public int Quantity { get; set; }

        // --- HATA DÜZELTEN KISIMLAR ---

        [Column("Product_id")] // Veritabanındaki "Product_id" sütunuyla eşleştirir
        public int Product_id { get; set; }

        [Column("Warehouse_id")] // Veritabanındaki "Warehouse_id" sütunuyla eşleştirir
        public int Warehouse_id { get; set; }

        [Column("User_id")] // Veritabanındaki "User_id" sütunuyla eşleştirir
        public int User_id { get; set; }

        public virtual product product { get; set; }
        public virtual user user { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}