//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_item
    {
        public int Id { get; set; }
        public int Product_id { get; set; }
        public int Warehouse_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Last_purchase_price { get; set; }
    
        public virtual product product { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
